### ISSUE TITLE
NullPointerException triggered by player login when AFKPlus_Status placeholder is used in tablist

### ISSUE THREAD

**Issue by TheMrEngMan** [Dart2112/AFKPlusPAPI#2]
When using the `AFKPlus_Status` placeholder provided by Afkpluspapi, there is sometimes an NullPointerException caused initially when a player logs in:
```
[12:33:28] [Server thread/INFO]: [redacted][/redacted:57564] logged in with entity id 86942 at ([survival]545.6999999880791, 42.0, 164.30000001192093)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: java.lang.NullPointerException
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at net.lapismc.afkplus.AFKPlus.getPlayer(AFKPlus.java:92)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at net.lapismc.afkplus.api.AFKPlusPlayerAPI.getPlayer(AFKPlusPlayerAPI.java:56)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at net.lapismc.afkpluspapi.PAPIHook.onPlaceholderRequest(PAPIHook.java:26)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:34)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:156)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:69)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:97)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at hu.montlikadani.tablist.bukkit.utils.Variables.setPlaceholders(Variables.java:241)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at hu.montlikadani.tablist.bukkit.utils.Variables.replaceVariables(Variables.java:162)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at hu.montlikadani.tablist.bukkit.TabListPlayer.getSuffix(TabListPlayer.java:261)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at hu.montlikadani.tablist.bukkit.TabListPlayer.getCustomTabName(TabListPlayer.java:267)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at hu.montlikadani.tablist.bukkit.tablist.groups.ReflectionHandled.setTeam(ReflectionHandled.java:81)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at hu.montlikadani.tablist.bukkit.Groups.setPlayerTeam(Groups.java:165)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at hu.montlikadani.tablist.bukkit.Groups.updatePlayers(Groups.java:292)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at hu.montlikadani.tablist.bukkit.Groups.lambda$startTask$0(Groups.java:269)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:33:28] [Craft Scheduler Thread - 1251/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
This repeats about 10 times

Followed by:
```
[17:07:18] [Craft Scheduler Thread - 2140/WARN]: java.lang.NullPointerException
[17:07:18] [Craft Scheduler Thread - 2139/WARN]: java.lang.NullPointerException
```
Being spammed in the console every second.

I've also noticed while another player logged in (in the same server session as the above errors), another exception:
```
[17:07:16] [Server thread/INFO]: [redacted][/redacted:60944] logged in with entity id 168899 at ([survival]-126.66186848210126, 84.0, -7052.463444635633)
[17:07:17] [Craft Scheduler Thread - 2135/WARN]: [TabList] Plugin TabList v5.5.2 generated an exception while executing task 100751312
java.lang.NullPointerException: null
```

I am using this plugin for my tablist: https://www.spigotmc.org/resources/animated-tab-tablist.46229

This error does *not* happen every time a player logs in, but only rarely.
When the player which triggered the issue leaves, the NullPointerException warnings do *not* stop being spammed in the console.

__Versions:__
AFKPlus -> 3.2.6 (latest)
Afkpluspapi -> 0.2.0 (latest)
TabList -> 5.5.2 (latest)
PlaceholderAPI -> 2.10.9 (latest)
Server is running on PaperMC build #455 (1.16.5)

**Comment by Dart2112** [comment]
I'm sorry, but notifications for this repo seem to be off. 
Which means I have missed years of issues posted here. I've rectified the issue so that I should be assigned to issues from now on and am currently handling the backlog.
Looking at your issue, I don't believe throwing a null pointer in that part of the code in the current versions of AFKPlus and AFKPlusPAPI should be possible. As such I will ask if this issue persists and close this issue if I don't get a response. If the issue does persist, please provide an updated error. Thanks
